"""add otp and refresh token to users

Revision ID: 13ac9a72398f
Revises: 7ac3f533e2e3
Create Date: 2026-03-10 12:44:42.207117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13ac9a72398f'
down_revision: Union[str, Sequence[str], None] = '7ac3f533e2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'landlord'),
               nullable=False,
               existing_server_default=sa.text("'landlord'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'landlord'),
               nullable=True,
               existing_server_default=sa.text("'landlord'"))
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'reset_otp_expiry')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
