"""add full models

Revision ID: 271b09ac623c
Revises: 4cf44aef134f
Create Date: 2026-03-11 09:31:45.972412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '271b09ac623c'
down_revision: Union[str, Sequence[str], None] = '4cf44aef134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('tenants', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('national_id', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('lease_start', sa.Date(), nullable=False))
    op.add_column('tenants', sa.Column('lease_end', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('tenants', sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('deposit_paid', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.Enum('active', 'inactive', 'evicted', name='tenantstatus'), nullable=True))
    op.add_column('tenants', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('tenants', 'unit_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(op.f('tenants_ibfk_2'), 'tenants', type_='foreignkey')
    op.drop_constraint(op.f('tenants_ibfk_1'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenants', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_ibfk_1'), 'tenants', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('tenants_ibfk_2'), 'tenants', 'units', ['unit_id'], ['id'])
    op.alter_column('tenants', 'unit_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'deposit_paid')
    op.drop_column('tenants', 'deposit_amount')
    op.drop_column('tenants', 'monthly_rent')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'lease_start')
    op.drop_column('tenants', 'emergency_contact_phone')
    op.drop_column('tenants', 'emergency_contact_name')
    op.drop_column('tenants', 'national_id')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'full_name')
    # ### end Alembic commands ###
