"""add deposit receipt path

Revision ID: 45b163e33a7f
Revises: 271b09ac623c
Create Date: 2026-03-11 15:41:43.897324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45b163e33a7f'
down_revision: Union[str, Sequence[str], None] = '271b09ac623c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('deposit_receipt_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'deposit_receipt_path')
    # ### end Alembic commands ###
