"""tenants payments notifications

Revision ID: 4cf44aef134f
Revises: 13ac9a72398f
Create Date: 2026-03-11 09:21:09.071671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cf44aef134f'
down_revision: Union[str, Sequence[str], None] = '13ac9a72398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.drop_column('properties', 'total_units')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.drop_column('tenants', 'move_out_date')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'national_id')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'rent_override')
    op.drop_column('tenants', 'deposit_amount')
    op.drop_column('tenants', 'full_name')
    op.drop_column('tenants', 'lease_start')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'deposit_paid_date')
    op.drop_column('tenants', 'deposit_paid')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'emergency_phone')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'emergency_name')
    op.alter_column('units', 'unit_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('bedsitter', 'one_bedroom', 'two_bedroom', 'three_bedroom', 'studio', 'shop', 'office', 'other', name='unittype'),
               existing_nullable=True)
    op.alter_column('units', 'rent_amount',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('units', 'status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('vacant', 'occupied', 'maintenance', name='unitstatus'),
               existing_nullable=True)
    op.alter_column('units', 'amenities',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_unique_constraint('uq_unit_in_property', 'units', ['property_id', 'unit_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_unit_in_property', 'units', type_='unique')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.alter_column('units', 'amenities',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('units', 'status',
               existing_type=sa.Enum('vacant', 'occupied', 'maintenance', name='unitstatus'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('units', 'rent_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('units', 'unit_type',
               existing_type=sa.Enum('bedsitter', 'one_bedroom', 'two_bedroom', 'three_bedroom', 'studio', 'shop', 'office', 'other', name='unittype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('tenants', sa.Column('emergency_name', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('tenants', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('tenants', sa.Column('emergency_phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('tenants', sa.Column('lease_end', sa.DATE(), nullable=True))
    op.add_column('tenants', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('deposit_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('deposit_paid_date', sa.DATE(), nullable=True))
    op.add_column('tenants', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('tenants', sa.Column('lease_start', sa.DATE(), nullable=False))
    op.add_column('tenants', sa.Column('full_name', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('tenants', sa.Column('deposit_amount', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('tenants', sa.Column('rent_override', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('tenants', sa.Column('notes', mysql.TEXT(), nullable=True))
    op.add_column('tenants', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('tenants', sa.Column('national_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('tenants', sa.Column('move_out_date', sa.DATE(), nullable=True))
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.add_column('properties', sa.Column('total_units', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    # ### end Alembic commands ###
