"""add deposit receipt path

Revision ID: 92ed7c493253
Revises: fa5e154d5fff
Create Date: 2026-03-11 15:46:00.346516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ed7c493253'
down_revision: Union[str, Sequence[str], None] = 'fa5e154d5fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_owner_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_unit_id'), table_name='tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_unit_id'), 'tenants', ['unit_id'], unique=False)
    op.create_index(op.f('ix_tenants_owner_id'), 'tenants', ['owner_id'], unique=False)
    # ### end Alembic commands ###
