"""add deposit receipt path

Revision ID: fa5e154d5fff
Revises: 45b163e33a7f
Create Date: 2026-03-11 15:44:08.696589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5e154d5fff'
down_revision: Union[str, Sequence[str], None] = '45b163e33a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op - deposit_receipt_path column already exists
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op - deposit_receipt_path column already exists
    pass
    # ### end Alembic commands ###
